language: python
python:
    - 3.6
    - 3.5
install:
    - pip install pipenv
    - pipenv install --dev --skip-lock
script: 
    - pipenv run pytest --flake8 --cov=gmeterpy
after_success:
    - codecov
notifications:
    email: false
