dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
install:
- pip install pipenv
- pipenv install --dev --skip-lock
script:
- pipenv run pytest gmeterpy --flake8 --cov=gmeterpy
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: iao
  password:
    secure: R2zbcBspVCFJ27LrBcFmZr2QxxhmuStI/wB2Q5kyqEJ2uMoN1G90+YZ9CupLxW5pUo764GZcxJlcAiXpJYR+VI8Or3tF5XCQwltNy6f2m5YGcuscfRp18VM1iV40c6wKE0zhr9XRn/mnUOU0DNtM2vPZDC99UooD2uO4bY1axqMPBDfHPqN7FpKyrZxVEY9s9b4rPJTLEPJPkXJtDd8J8DgS7keohhE0l96Um7wQTRg6yHKpsd44Qi9DgdKRTBDFw+cLRge9RCb8Y/pAsFd0yGVlaz2uprpb+MkvcbJem9OVHv1cX6NMtSPCjmvzTFpxbBg0cFFl+/DQ6OoUd27szXTbmNLmUVsu/G4Vf9H/zCLoJQdZudWrPwgj948hA39vl9einn3fJEdArvQVFJUr1sFi6a82KDYc8kFAQ6u2yNEhjXHJBKKOgT+qq5bFjWZHOcyV1zx6m9ilNSj+uoHa5ikMCLySx8ZjbDtIw/wDJBaxgRxw+h9vtu23P+X9WTckGU60jqRZOLtfNeACcnEDcfzLyA6NexZ93vSSXmy6r9Ep9vbgA5ZNyNbzdIJ1X6lZRUai8WIiuyiNXhV4Asl0RxO1STNo5pvaTQ37JHxHTdFEw7cU5yp33gzLJtOh5qUkc1VYXEX3xLBeDJCZSYWUUf5po/knwpztmGofxJvhkaw=
  on:
      tags: true
